// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkstyhjwjcmgbmhrooqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrc3R5aGp3amNtZ2JtaHJvb3FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDExNTksImV4cCI6MjA3MzI3NzE1OX0.yrn1QcYg-F7HEYmvU-9XZvw7pZGCxVjLv2Ay5WoIWFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});